export const DEFAULT_CATALOG_PAYLOADS: Record<string, Record<string, unknown>> = {
  products: {
    name: { ar: 'منتج جديد', en: 'New Product' },
    slug: 'new-product',
    description: { ar: 'وصف عربي', en: 'English description' },
    short_description: { ar: 'وصف مختصر', en: 'Short description' },
    base_price: 99,
    is_active: true,
    is_available_in_all_branches: true,
    is_best_seller_pinned: false,
    category_ids: [],
    tag_ids: [],
    branch_ids: [],
    main_image_path: '',
    media: [],
    sizes: [],
    addon_groups: [],
  },
  categories: {
    parent_id: null,
    name: { ar: 'قسم جديد', en: 'New Category' },
    slug: 'new-category',
    description: { ar: 'وصف القسم', en: 'Category description' },
    sort_order: 0,
    is_active: true,
  },
  tags: {
    name: { ar: 'وسم جديد', en: 'New Tag' },
    slug: 'new-tag',
    is_active: true,
  },
  branches: {
    name: { ar: 'فرع جديد', en: 'New Branch' },
    slug: 'new-branch',
    phone: '01000000000',
    email: 'branch@example.com',
    address: 'Cairo, Egypt',
    latitude: 30.0444,
    longitude: 31.2357,
    working_hours: {
      saturday: '10:00-23:00',
      sunday: '10:00-23:00',
    },
    is_active: true,
  },
  'delivery-zones': {
    branch_id: 1,
    name: { ar: 'منطقة جديدة', en: 'New Zone' },
    code: 'NEW-ZONE',
    delivery_fee: 25,
    min_delivery_time_minutes: 30,
    max_delivery_time_minutes: 60,
    is_active: true,
  },
  coupons: {
    code: 'NEW50',
    type: 'fixed',
    value: 50,
    applies_to: 'products',
    min_cart_value: 150,
    usage_limit_total: 100,
    usage_limit_per_user: 1,
    is_active: true,
    conditions: {},
  },
  'gift-cards': {
    code: 'GIFT250',
    amount: 250,
    currency_code: 'EGP',
    is_active: true,
    expires_at: null,
  },
  pages: {
    slug: 'new-page',
    title: { ar: 'صفحة جديدة', en: 'New Page' },
    content: { ar: 'محتوى عربي', en: 'English content' },
    is_active: true,
  },
};
